import { Product } from "@/types/types";

export const dummmyProducts: Product[] = [
    {
      product_id: 1,
      name: 'Summer Dress',
      description: 'A light and breezy summer dress.',
      price: '49.99',
      quantity: 5,
      seller_id: 'user_12345',
      category_id: 1,
      creation_date: '2024-09-27',
      bucket_key: `/src/assets/image_gallery/dress_62_0.jpg`,
    },
    {
      product_id: 2,
      name: 'Winter Jacket',
      description: 'A warm and comfortable winter jacket.',
      price: '89.99',
      quantity: 10,
      seller_id: 'user_54321',
      category_id: 2,
      creation_date: '2024-09-26',
      bucket_key: `/src/assets/image_gallery/dress_62_0.jpg`,
    },
    {
      product_id: 3,
      name: 'Casual T-shirt',
      description: 'A soft cotton t-shirt for everyday wear.',
      price: '19.99',
      quantity: 20,
      seller_id: 'user_67890',
      category_id: 3,
      creation_date: '2024-09-25',
      bucket_key: `/src/assets/image_gallery/dress_62_0.jpg`,
    },
    {
      product_id: 4,
      name: 'Leather Boots',
      description: 'Durable leather boots for all terrains.',
      price: '129.99',
      quantity: 8,
      seller_id: 'user_98765',
      category_id: 4,
      creation_date: '2024-09-24',
      bucket_key: `/src/assets/image_gallery/dress_62_0.jpg`,
    },
    {
      product_id: 5,
      name: 'Sports Shorts',
      description: 'Breathable shorts perfect for workouts.',
      price: '29.99',
      quantity: 15,
      seller_id: 'user_24680',
      category_id: 5,
      creation_date: '2024-09-23',
      bucket_key: `/src/assets/image_gallery/dress_62_0.jpg`,
    },
  ];